### PR TITLE
Add a description on how to add views to your Addon

### PR DESCRIPTION
**Pull request by jonassiewertsen**
A grammar check would be needed :-)

### CODE REVIEW

**Comment by jasonvarga** [comment]
I think it would be way more useful for us to just wire this up to be automatic.

Behind the scenes we could call `$this->loadViewsFrom('path/to/their/resources/views/', 'addon-name');`

Where `addon-name` would be the second part of their composer package (eg. `vendor/addon-name`)

If they have a `resources/views` directory, they should just be able to assume `view('addon-name::myview')` would work.

**Comment by jonassiewertsen** [comment]
Personally, I would enjoy it the "Laravel way" without any automation. 

Especially in custom addons, it's nice to stay in control. 

Let me know if you plan to automate it. I am more than happy to adjust the description!

**Comment by jasonvarga** [comment]
Already automated (https://github.com/statamic/cms/commit/c8c7587bb4ba8b47abc73f889cd7a8a5d07b38a4), and docs done (https://github.com/statamic/docs/commit/14311273a3c3a184cd39da258a7019eea43cd74a). Thanks for offering though!

You're free to continue to do what you're doing though, if you want to put your views somewhere non-standard or use a different namespace.

**Comment by jonassiewertsen** [comment]
Ohh, I did not know about the automation. 

It wasn't there in Dec 2019 :-)

Thanks!

**Comment by jasonvarga** [comment]
It wasn't. I just added it today!

**Comment by jasonvarga** [comment]
And now you can customize the namespace, if that's one of the reasons you'd want more control. (20698303)

**Comment by jonassiewertsen** [comment]
That looks good Jason!

**Pull request closed without merging**
