### PR TITLE
Update git-integration.md

### PR DESCRIPTION
**Pull request by robdekort**
Add examples for Forge and Ploi on how to skip deployment when using git integration and when you use a custom commit message.

### CODE REVIEW

**Comment by jackmcdade** [comment]
I've never heard of Ploi, interesting. Would you be able to add links to right services so the context won't be missed?

**Comment by jackmcdade** [comment]
Great, thank you!

**Comment by robdekort** [comment]
Done! Yeah, Ploi looks great. We've been talking about it in the server channel often on Discord. Some people use it and really prefer it over Forge. I'd like to switch but it's a lot of work.

**Comment by robdekort** [comment]
Welcome! It's cheaper, has more features (something like envoyer bascially included) and development and support is very active.

**Pull request merged**
