### PR TITLE
Update all composer deps, including Statamic

### PR DESCRIPTION
**Pull request by edalzell**
Seems to work with my formalized testing method of click-around-on-a-few-things.

### CODE REVIEW

**Comment by jasonvarga** [comment]
What's the reason for the update?

**Comment by edalzell** [comment]
Site wouldn't load locally for me, thought I'd try to upgrade and see if it fixed it, which it did. Also, staying current is a decent plan n'est pas?

**Comment by jasonvarga** [comment]
What was broken?

**Comment by edalzell** [comment]
Something to do with `[$statamic]` not defined, I think. I can switch to base branch and put an issue in if you'd prefer. Making a docs PR and wanted to have a local site to review against, no biggie if you don't want to do this.

**Comment by edalzell** [comment]
switched back, seems to work now, close if you don't want to update.

**Comment by jasonvarga** [comment]
Yeah let us know if there's an issue. Thanks for the PR though.

**Pull request closed without merging**
