### PR TITLE
Add store as reserved field word

### PR DESCRIPTION
**Pull request by robdekort**
It only took me three hours to find this out...

### CODE REVIEW

**Comment by jackmcdade** [comment]
If this is true it should be added to the FieldsController as well: <https://github.com/statamic/cms/blob/3.2/src/Http/Controllers/CP/Fields/FieldsController.php#L71-L82>

**Comment by jasonvarga** [comment]
I don't see why it should be reserved. Maybe we can fix the underlying problem.

**Comment by robdekort** [comment]
You can check my support mail, it has a zip attached.

**Comment by robdekort** [comment]
Reach out when you have q's of course!

**Comment by jasonvarga** [comment]
Closing this, we'll sort it out over support.

**Pull request closed without merging**
