### PR TITLE
Add an extra introduction on how to get started extending Bard.

### LINKED ISSUE #424: Extending Bard docs
This whole page is unfortunately very unclear to me: https://statamic.dev/extending/bard#extensions

In my opinion it would benefit from the following:

- What is TipTap (in relation to Statamic and Bard)
- What is ProseMirror (in relation to Statamic and Bard)
- What is Mark
- Where do you put this JS Code
- What is ProseMirror rendering
- TipTap library / API?
- Example: simple button that does a simple thing like adding a class or wrapping in stuff in an element
- Less assumed knowledge

### PR DESCRIPTION
**Pull request by jelleroorda**
Closes #424.

### CODE REVIEW

**Comment by jelleroorda** [comment]
@robdekort Can you check if you're still missing things, whether things are unclear, or would need any further pointers for?

**Comment by robdekort** [comment]
Nice, I think this really really helps a lot. It's already way clearer to me. Although I'm fairly positive now I'm def. not gonna burn my hands on extending Bard, which is based on TipTap, which is a wrapper around ProseMirror 🤯

😉

**Comment by jelleroorda** [comment]
Well it’s definitely something that will cost you a lot of time, and is also pretty prone to bugs if you ask me... so that’s probably a wise choice 😉

**Comment by jackmcdade** [comment]
Thanks for the fellas! Made a few little tweaks but this is super helpful. Much appreciated!

**Pull request merged**
