### PR TITLE
fortrabbit deployment guide proposal

### PR DESCRIPTION
**Pull request by frank-laemmer**
Instead of linking to the fortrabbit docs, have an article on statamic.dev that better matches the structure of the other deployment articles.

### CODE REVIEW

**Comment by jackmcdade** [comment]
Awesome! Will get this reviewed and hopefully up in short order ❤️

**Comment by frank-laemmer** [comment]
Oh. Fast. Discussed this recently with @joshuablum. Add/change/remove as required. I am available for questions regarding fortrabbit.

**Comment by frank-laemmer** [comment]
I see this is not merged, but some edits have been done. I am happy to discuss any questions.

**Comment by joshuablum** [comment]
Merging this and making a few little changes afterwards 👍

**Pull request merged**
