### PR TITLE
Fix a few broken links

### PR DESCRIPTION
**Pull request by JonKaric**

### CODE REVIEW

**Comment by duncanmcclean** [comment]
Hey, would you mind adding `Closes #443` to the PR description? It'll mean that when this PR is merged, the related issue will automatically be closed. Thanks!

**Comment by JonKaric** [comment]
This doesn't fix #443, they're two separate issues

**Comment by duncanmcclean** [comment]
Ah sorry, I just presumed as they both had to do with broken links. Ignore me 😅

**Comment by jackmcdade** [comment]
Thanks!

**Pull request merged**
