### PR TITLE
Update antlers.md

### PR DESCRIPTION
**Pull request by Ash-LightAndShape**
Added a link to my Nova Antlers extension :)

Very useful for the 8 people using Nova.

### CODE REVIEW

**Comment by joshuablum** [comment]
Hey @Ash-LightAndShape,

Your PR doesn't include any actual changes? There is one commit but there are no changes associated with it. Also, we usually try to avoid to link to third-party packages. Could you please elaborate on its use?

Closing this for now.

**Comment by Ash-LightAndShape** [comment]
Very odd that came through empty! I had some form weirdness when was making the PR so might be something to do with that

It's a link in IDE integrations section for the extension I published recently for Nova https://nova.app 

Up to you if you want it including, if so I'll create a new PR
Screenshot 2023-09-30 at 11 51 52

**Comment by joshuablum** [comment]
Whoops, I thought it was related to [Laravel Nova](https://nova.laravel.com/), @Ash-LightAndShape. Wouldn't have happened if the PR contained the change of course, sorry. Would have seen what it is then. Including this extension in the list makes perfect sense of course. Thanks for the PR and for creating the extension in the first place, much appreaciated! Please add the updated file and commit again so it can get merged 🙂 I can't push to your fork.

**Comment by Ash-LightAndShape** [comment]
Ah! Yeah, that makes sense!

**Comment by joshuablum** [comment]
Thanks!

**Pull request merged**
