### PR TITLE
Add markdown template section to forms documentation

### PR DESCRIPTION
**Pull request by ArronKing**
Add some instructions to the forms documentation that explains how to use the Laravel Markdown templates in Statamic.

### CODE REVIEW

**Comment by duncanmcclean** [comment]
Thanks!

For some reason, I wasn't able to push my edits up to your branch so I've pushed these changes straight to `master` in 871b248.

**Comment by ArronKing** [comment]
No problem - looks good, but one of the yaml blocks looks like it's duplicated.

**Comment by duncanmcclean** [comment]
The YAML blocks aren't total duplicates. One shows the need for the `markdown` setting and the other shows the need to specify the view. 

image

**Comment by ArronKing** [comment]
Sorry Duncan - I didn't notice that. Re-reading it all looks good!

**Pull request closed without merging**
