### PR TITLE
Update form-create.md

### PR DESCRIPTION
**Pull request by robdekort**
Explain how to dynamically render a selected form via the Form Fieldtype. Question comes up often.

### CODE REVIEW

**Comment by jackmcdade** [comment]
Have you tried `{{ form:create :in="form_fieldtype:handle" }}`? If that works (it should), would you mind updating it? Interpolation over vars-in-params is our preferred syntax. 😊

**Comment by robdekort** [comment]
Yes that is nicer. I'll check right away.

**Comment by robdekort** [comment]
Doesn't work.

**Comment by jackmcdade** [comment]
:poop:

**Pull request merged**
