### PR TITLE
add config tag

### PR DESCRIPTION
**Pull request by edalzell**
You might want/need to "statamify" the language.

### CODE REVIEW

**Comment by jesseleite** [comment]
Main problem with this is that it's not a tag.  It's just array data that's passed into your views, which you can see if you `{{ dump }}`.

**Comment by edalzell** [comment]
This should be re-worded then?
image

**Comment by jesseleite** [comment]
Yeah that sounds good, and maybe not in the `/tags` part of the docs, since it's technically not a tag.

**Comment by edalzell** [comment]
Sorry @jesseleite, I'm confused with your comment. So not a tag? If so, there's not really anything to change?

Issue is that it doesn't show up in a search so people can't find it.

**Comment by jasonvarga** [comment]
Pushed a commit and made some tweaks. It should become searchable soon once Algolia does its magic.

**Pull request closed without merging**
