### PR TITLE
Path incorrect for config app. This does not work.

### PR DESCRIPTION
**Pull request by icemancast**
Tried the suggested and it did not, then realized the path noted for the config is incorrect.

### CODE REVIEW

**Comment by jasonvarga** [comment]
The path was correct. Perhaps you can explain what wasn’t working for you?

**Comment by icemancast** [comment]
One there is not config/statamic/app.php file in v3 using beta 22 so I created one. After that I tried using the suggest {{ config:app:awesome }} and it doesn't not reference the path described. 

Then tested the addition of the value inside config/app.php with the {{ config:app:awesome }} template tag and that works perfectly.

**Comment by jasonvarga** [comment]
The environment variables section applies to config files in general. Not specific to the ones in the statamic subdirectory.

**Comment by icemancast** [comment]
I understand that so noted above the config tag is: `config/statamic/app.php` which is statamic specific. It caused some confusion if that makes sense.

**Pull request closed without merging**
