### PR TITLE
group_by example

### PR DESCRIPTION
**Pull request by robdekort**
Two collections:
* Blog
* Author

This will fetch you a list of authors that wrote a blog post.

### CODE REVIEW

**Comment by jackmcdade** [comment]
Hmm, not sure it's described quite right. Do you mean blog collection and author _field_? Also, an output might help users grok the example better.

**Comment by robdekort** [comment]
Does this help? It came up in discord and Erin and I found it a nice solution as it's native antlers. Figured it would be nice in the docs.

**Comment by jackmcdade** [comment]
I don't see any interaction with the authors collection in this example though – am i misunderstanding what you're doing? I'm sorry I'm so confused here.

**Comment by robdekort** [comment]
Haha that's ok. Means my PR is not clear right? I'll add to it. Def. interacting with authors. See the group_by attribute.

**Comment by robdekort** [comment]
Ok one more try because I really like you Jack....

**Comment by jackmcdade** [comment]
I think this confuses me because I wouldn't use an Author collection, i'd just use the users for that. Plus, `author` is a special field name that enables the per-user permissions inside Collections. 🤔

**Pull request closed without merging**
