### PR TITLE
Update design and content starter kits

### PR DESCRIPTION
**Pull request by robdekort**
Use the same design language as on the main page for the starter kits.

### CODE REVIEW

**Comment by jasonvarga** [comment]
@jackmcdade if you're cool with community starter kits being shown on the docs home page, then smash that merge button.

**Comment by robdekort** [comment]
Oh yeah, nice Jason. I couldn't see the result here myself 😂.

**Comment by robdekort** [comment]
An alternative idea could be to link to the installation page beneath the official kits to let users know there's community based stuff.

**Comment by jackmcdade** [comment]
I'm fine with it for now, but might need to remove them once we make the push for more starter kits – I hope that there will be to many to show favoritism and rather just link to the Marketplace.

**Comment by robdekort** [comment]
Can’t come soon enough!

**Pull request merged**
