### PR TITLE
Make the docs vegan friendly

### PR DESCRIPTION
**Pull request by tao**
Removed the duplicate Antlers output and made the documentation vegan friendly.

### CODE REVIEW

**Comment by jasonvarga** [comment]
Can't we compromise? 

image

**Comment by tao** [comment]
Pizza is a compromise compared to Kale ;) and personally Pizza reminds me a lot more of the Statamic 80’s / early 90’s / futuristic / hacker vibe than Bacon does.

**Comment by alexharrell** [comment]
I agree with pizza, as a bacon lover, I would be offended by any "Facon".

**Comment by jasonvarga** [comment]
You're right. Pizza can be enjoyed by everyone. Meat lovers, vegans, and turtles.

**Comment by jackmcdade** [comment]
But what about the gluten?

**Comment by jesseleite** [comment]
I’m allergic to the dairy, can we compromise with ‘vitamin water’?

**Comment by jackmcdade** [comment]
What about essential oils?

**Comment by tao** [comment]
<3 is shaped like pizza for a reason :smile:

**Pull request merged**
