### PR TITLE
where clauses with collection do not need an operator

### PR DESCRIPTION
**Pull request by j3ll3yfi5h**

### CODE REVIEW

**Comment by jackmcdade** [comment]
That is true, but that block right there is explaining how it works so we want to show the full method declaration and then teach the shorthand. You'll notice we don't use 3 argument blocks anywhere else unless necessary. :) Thanks though!

**Comment by j3ll3yfi5h** [comment]
@jackmcdade but it did not work like this in my current project, I still think its wrong. Am I wrong?

**Comment by jackmcdade** [comment]
What do you mean? What did you try specifically and what error did you receive specifically?

**Comment by jasonvarga** [comment]
Yeah it doesn't work if you add the operator. Specifically for `where('collection'`

**Pull request closed without merging**
